version: '3.3'
services:
  redis:
    image: redis
    container_name: redis-server
    env_file:
      - .production.env
    ports:
      - 6379:6379
    volumes:
      - ./redis/data/redis:/data
      - ./redis/config/redis.conf:/redis.conf
    command: redis-server /redis.conf --requirepass ${REDIS_PASSWORD}
    networks:
      - app-net

  redis-mgmt:
    image: rediscommander/redis-commander:latest
    container_name: redis-management
    env_file:
      - .production.env
    ports:
      - 8081:8081
    restart: always
    networks:
      - app-net

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery-worker
    command: celery -A celery_worker.celery worker -l info
    volumes:
      - .:/app
    env_file:
      - .production.env
    networks:
      - app-net
  
  flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: flower
    command: celery -A celery_worker.celery flower --port=5555
    ports:
      - 5556:5555
    env_file:
      - .production.env
    networks:
      - app-net
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    env_file:
      - .production.env
    ports:
      - 8000:8000
    networks:
      - app-net

networks:
  app-net:
